/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thai.intellijentEC.main.ui;

/**
 *
 * @author 段晓强
 */
public class SendChoose extends javax.swing.JFrame {

    /**
     * Creates new form SendChoose
     */
    public SendChoose() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelTopBar = new javax.swing.JPanel();
        btn_return = new javax.swing.JButton();
        lab_time = new javax.swing.JLabel();
        lab_title = new javax.swing.JLabel();
        lab_canchoose = new javax.swing.JLabel();
        lab_cantchoose = new javax.swing.JLabel();
        G01 = new javax.swing.JButton();
        G02 = new javax.swing.JButton();
        G03 = new javax.swing.JButton();
        G04 = new javax.swing.JButton();
        G05 = new javax.swing.JButton();
        G06 = new javax.swing.JButton();
        H01 = new javax.swing.JButton();
        H02 = new javax.swing.JButton();
        H03 = new javax.swing.JButton();
        F01 = new javax.swing.JButton();
        F03 = new javax.swing.JButton();
        F05 = new javax.swing.JButton();
        D03 = new javax.swing.JButton();
        D05 = new javax.swing.JButton();
        E01 = new javax.swing.JButton();
        D01 = new javax.swing.JButton();
        E03 = new javax.swing.JButton();
        E05 = new javax.swing.JButton();
        F02 = new javax.swing.JButton();
        F04 = new javax.swing.JButton();
        F06 = new javax.swing.JButton();
        D04 = new javax.swing.JButton();
        D06 = new javax.swing.JButton();
        E02 = new javax.swing.JButton();
        D02 = new javax.swing.JButton();
        E04 = new javax.swing.JButton();
        E06 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_screen = new javax.swing.JButton();
        B05 = new javax.swing.JButton();
        C01 = new javax.swing.JButton();
        C03 = new javax.swing.JButton();
        C05 = new javax.swing.JButton();
        A03 = new javax.swing.JButton();
        A05 = new javax.swing.JButton();
        B01 = new javax.swing.JButton();
        A01 = new javax.swing.JButton();
        B03 = new javax.swing.JButton();
        B06 = new javax.swing.JButton();
        C02 = new javax.swing.JButton();
        C04 = new javax.swing.JButton();
        C06 = new javax.swing.JButton();
        A04 = new javax.swing.JButton();
        A06 = new javax.swing.JButton();
        B02 = new javax.swing.JButton();
        A02 = new javax.swing.JButton();
        B04 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanelTopBar.setBackground(new java.awt.Color(251, 205, 57));

        btn_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/intellijentEC/resources/btn_return.png"))); // NOI18N

        lab_time.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        lab_time.setForeground(new java.awt.Color(255, 255, 255));
        lab_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_time.setText("58s");

        javax.swing.GroupLayout jPanelTopBarLayout = new javax.swing.GroupLayout(jPanelTopBar);
        jPanelTopBar.setLayout(jPanelTopBarLayout);
        jPanelTopBarLayout.setHorizontalGroup(
            jPanelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_return, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lab_time, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTopBarLayout.setVerticalGroup(
            jPanelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopBarLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lab_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_return, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lab_title.setFont(new java.awt.Font("微软雅黑", 0, 64)); // NOI18N
        lab_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_title.setText("请点选快递柜");

        lab_canchoose.setFont(new java.awt.Font("微软雅黑", 0, 21)); // NOI18N
        lab_canchoose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_canchoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/intellijentEC/resources/can_choose.png"))); // NOI18N
        lab_canchoose.setText("可选");

        lab_cantchoose.setFont(new java.awt.Font("微软雅黑", 0, 21)); // NOI18N
        lab_cantchoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/intellijentEC/resources/cant_choose.png"))); // NOI18N
        lab_cantchoose.setText("占用");

        G01.setBackground(new java.awt.Color(255, 160, 10));
        G01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G01ActionPerformed(evt);
            }
        });

        G02.setBackground(new java.awt.Color(255, 160, 10));
        G02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G02ActionPerformed(evt);
            }
        });

        G03.setBackground(new java.awt.Color(255, 160, 10));
        G03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G03ActionPerformed(evt);
            }
        });

        G04.setBackground(new java.awt.Color(255, 160, 10));
        G04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G04ActionPerformed(evt);
            }
        });

        G05.setBackground(new java.awt.Color(255, 160, 10));
        G05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G05ActionPerformed(evt);
            }
        });

        G06.setBackground(new java.awt.Color(255, 160, 10));
        G06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G06ActionPerformed(evt);
            }
        });

        H01.setBackground(new java.awt.Color(255, 160, 10));
        H01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H01ActionPerformed(evt);
            }
        });

        H02.setBackground(new java.awt.Color(255, 160, 10));
        H02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H02ActionPerformed(evt);
            }
        });

        H03.setBackground(new java.awt.Color(255, 160, 10));
        H03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H03ActionPerformed(evt);
            }
        });

        F01.setBackground(new java.awt.Color(255, 160, 10));
        F01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F01ActionPerformed(evt);
            }
        });

        F03.setBackground(new java.awt.Color(255, 160, 10));
        F03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F03ActionPerformed(evt);
            }
        });

        F05.setBackground(new java.awt.Color(255, 160, 10));
        F05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F05ActionPerformed(evt);
            }
        });

        D03.setBackground(new java.awt.Color(255, 160, 10));
        D03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D03ActionPerformed(evt);
            }
        });

        D05.setBackground(new java.awt.Color(255, 160, 10));
        D05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D05ActionPerformed(evt);
            }
        });

        E01.setBackground(new java.awt.Color(255, 160, 10));
        E01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E01ActionPerformed(evt);
            }
        });

        D01.setBackground(new java.awt.Color(255, 160, 10));
        D01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D01ActionPerformed(evt);
            }
        });

        E03.setBackground(new java.awt.Color(255, 160, 10));
        E03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E03ActionPerformed(evt);
            }
        });

        E05.setBackground(new java.awt.Color(255, 160, 10));
        E05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E05ActionPerformed(evt);
            }
        });

        F02.setBackground(new java.awt.Color(255, 160, 10));
        F02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F02ActionPerformed(evt);
            }
        });

        F04.setBackground(new java.awt.Color(255, 160, 10));
        F04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F04ActionPerformed(evt);
            }
        });

        F06.setBackground(new java.awt.Color(255, 160, 10));
        F06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F06ActionPerformed(evt);
            }
        });

        D04.setBackground(new java.awt.Color(255, 160, 10));
        D04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D04ActionPerformed(evt);
            }
        });

        D06.setBackground(new java.awt.Color(255, 160, 10));
        D06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D06ActionPerformed(evt);
            }
        });

        E02.setBackground(new java.awt.Color(255, 160, 10));
        E02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E02ActionPerformed(evt);
            }
        });

        D02.setBackground(new java.awt.Color(255, 160, 10));
        D02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D02ActionPerformed(evt);
            }
        });

        E04.setBackground(new java.awt.Color(255, 160, 10));
        E04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E04ActionPerformed(evt);
            }
        });

        E06.setBackground(new java.awt.Color(255, 160, 10));
        E06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E06ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 96, 10));

        btn_screen.setBackground(new java.awt.Color(255, 176, 133));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_screen, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btn_screen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        B05.setBackground(new java.awt.Color(255, 160, 10));
        B05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B05ActionPerformed(evt);
            }
        });

        C01.setBackground(new java.awt.Color(255, 160, 10));
        C01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C01ActionPerformed(evt);
            }
        });

        C03.setBackground(new java.awt.Color(255, 160, 10));
        C03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C03ActionPerformed(evt);
            }
        });

        C05.setBackground(new java.awt.Color(255, 160, 10));
        C05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C05ActionPerformed(evt);
            }
        });

        A03.setBackground(new java.awt.Color(255, 160, 10));
        A03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A03ActionPerformed(evt);
            }
        });

        A05.setBackground(new java.awt.Color(255, 160, 10));
        A05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A05ActionPerformed(evt);
            }
        });

        B01.setBackground(new java.awt.Color(255, 160, 10));
        B01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B01ActionPerformed(evt);
            }
        });

        A01.setBackground(new java.awt.Color(255, 160, 10));
        A01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A01ActionPerformed(evt);
            }
        });

        B03.setBackground(new java.awt.Color(255, 160, 10));
        B03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B03ActionPerformed(evt);
            }
        });

        B06.setBackground(new java.awt.Color(255, 160, 10));
        B06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B06ActionPerformed(evt);
            }
        });

        C02.setBackground(new java.awt.Color(255, 160, 10));
        C02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C02ActionPerformed(evt);
            }
        });

        C04.setBackground(new java.awt.Color(255, 160, 10));
        C04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C04ActionPerformed(evt);
            }
        });

        C06.setBackground(new java.awt.Color(255, 160, 10));
        C06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C06ActionPerformed(evt);
            }
        });

        A04.setBackground(new java.awt.Color(255, 160, 10));
        A04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A04ActionPerformed(evt);
            }
        });

        A06.setBackground(new java.awt.Color(255, 160, 10));
        A06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A06ActionPerformed(evt);
            }
        });

        B02.setBackground(new java.awt.Color(255, 160, 10));
        B02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B02ActionPerformed(evt);
            }
        });

        A02.setBackground(new java.awt.Color(255, 160, 10));
        A02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A02ActionPerformed(evt);
            }
        });

        B04.setBackground(new java.awt.Color(255, 160, 10));
        B04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B04ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lab_canchoose, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lab_cantchoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lab_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(G02, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G01, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G03, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G04, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G05, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G06, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H01, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H02, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H03, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(D01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(D03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(D05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(E01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(E03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(E05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(F01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(F03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(F05, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(E02, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E04, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E06, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F02, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F04, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F06, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D04, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D02, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D06, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(A01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(A03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(A05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C05, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(A02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(A04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(A06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C06, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lab_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lab_canchoose, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(lab_cantchoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(G01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G03, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G04, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G05, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G06, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H01, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H02, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H03, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(D01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D03, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D05, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E03, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E05, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F01, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F03, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F05, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(D02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D04, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D06, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E04, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E06, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F02, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F04, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F06, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(A01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(A03, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(A05, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B03, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B05, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C01, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C03, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C05, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(A02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A04, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A06, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B04, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B06, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C02, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C04, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C06, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void G01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G01ActionPerformed

    private void G02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G02ActionPerformed

    private void G03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G03ActionPerformed

    private void G04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G04ActionPerformed

    private void G05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G05ActionPerformed

    private void G06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G06ActionPerformed

    private void H01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H01ActionPerformed

    private void H02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H02ActionPerformed

    private void H03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H03ActionPerformed

    private void F01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F01ActionPerformed

    private void F03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F03ActionPerformed

    private void F05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F05ActionPerformed

    private void D03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D03ActionPerformed

    private void D05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D05ActionPerformed

    private void E01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E01ActionPerformed

    private void D01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D01ActionPerformed

    private void E03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E03ActionPerformed

    private void E05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E05ActionPerformed

    private void F02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F02ActionPerformed

    private void F04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F04ActionPerformed

    private void F06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F06ActionPerformed

    private void D04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D04ActionPerformed

    private void D06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D06ActionPerformed

    private void E02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E02ActionPerformed

    private void D02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D02ActionPerformed

    private void E04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E04ActionPerformed

    private void E06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E06ActionPerformed

    private void B05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B05ActionPerformed

    private void C01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C01ActionPerformed

    private void C03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C03ActionPerformed

    private void C05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C05ActionPerformed

    private void A03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A03ActionPerformed

    private void A05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A05ActionPerformed

    private void B01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B01ActionPerformed

    private void A01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A01ActionPerformed

    private void B03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B03ActionPerformed

    private void B06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B06ActionPerformed

    private void C02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C02ActionPerformed

    private void C04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C04ActionPerformed

    private void C06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C06ActionPerformed

    private void A04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A04ActionPerformed

    private void A06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A06ActionPerformed

    private void B02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B02ActionPerformed

    private void A02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A02ActionPerformed

    private void B04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B04ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendChoose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A01;
    private javax.swing.JButton A02;
    private javax.swing.JButton A03;
    private javax.swing.JButton A04;
    private javax.swing.JButton A05;
    private javax.swing.JButton A06;
    private javax.swing.JButton B01;
    private javax.swing.JButton B02;
    private javax.swing.JButton B03;
    private javax.swing.JButton B04;
    private javax.swing.JButton B05;
    private javax.swing.JButton B06;
    private javax.swing.JButton C01;
    private javax.swing.JButton C02;
    private javax.swing.JButton C03;
    private javax.swing.JButton C04;
    private javax.swing.JButton C05;
    private javax.swing.JButton C06;
    private javax.swing.JButton D01;
    private javax.swing.JButton D02;
    private javax.swing.JButton D03;
    private javax.swing.JButton D04;
    private javax.swing.JButton D05;
    private javax.swing.JButton D06;
    private javax.swing.JButton E01;
    private javax.swing.JButton E02;
    private javax.swing.JButton E03;
    private javax.swing.JButton E04;
    private javax.swing.JButton E05;
    private javax.swing.JButton E06;
    private javax.swing.JButton F01;
    private javax.swing.JButton F02;
    private javax.swing.JButton F03;
    private javax.swing.JButton F04;
    private javax.swing.JButton F05;
    private javax.swing.JButton F06;
    private javax.swing.JButton G01;
    private javax.swing.JButton G02;
    private javax.swing.JButton G03;
    private javax.swing.JButton G04;
    private javax.swing.JButton G05;
    private javax.swing.JButton G06;
    private javax.swing.JButton H01;
    private javax.swing.JButton H02;
    private javax.swing.JButton H03;
    private javax.swing.JButton btn_return;
    private javax.swing.JButton btn_screen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelTopBar;
    private javax.swing.JLabel lab_canchoose;
    private javax.swing.JLabel lab_cantchoose;
    private javax.swing.JLabel lab_time;
    private javax.swing.JLabel lab_title;
    // End of variables declaration//GEN-END:variables
}
