/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thai.intellijentEC.admin.ui;

/**
 *
 * @author 段晓强
 */
public class ManageInput extends javax.swing.JFrame {

    /**
     * Creates new form ManageInput
     */
    public ManageInput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_return = new javax.swing.JButton();
        lab_time = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        key_1 = new javax.swing.JButton();
        key_2 = new javax.swing.JButton();
        key_3 = new javax.swing.JButton();
        key_4 = new javax.swing.JButton();
        key_5 = new javax.swing.JButton();
        key_6 = new javax.swing.JButton();
        key_7 = new javax.swing.JButton();
        key_8 = new javax.swing.JButton();
        key_9 = new javax.swing.JButton();
        key_0 = new javax.swing.JButton();
        key_back = new javax.swing.JButton();
        key_q = new javax.swing.JButton();
        key_w = new javax.swing.JButton();
        key_e = new javax.swing.JButton();
        key_r = new javax.swing.JButton();
        key_u = new javax.swing.JButton();
        key_i = new javax.swing.JButton();
        key_t = new javax.swing.JButton();
        key_y = new javax.swing.JButton();
        key_o = new javax.swing.JButton();
        key_p = new javax.swing.JButton();
        key_d = new javax.swing.JButton();
        key_f = new javax.swing.JButton();
        key_j = new javax.swing.JButton();
        key_k = new javax.swing.JButton();
        key_g = new javax.swing.JButton();
        key_h = new javax.swing.JButton();
        key_l = new javax.swing.JButton();
        key_a = new javax.swing.JButton();
        key_s = new javax.swing.JButton();
        key_m = new javax.swing.JButton();
        key_change = new javax.swing.JButton();
        key_b = new javax.swing.JButton();
        key_n = new javax.swing.JButton();
        key_z = new javax.swing.JButton();
        key_x = new javax.swing.JButton();
        key_c = new javax.swing.JButton();
        key_v = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(251, 205, 57));

        btn_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thai/intellijentEC/resources/btn_return.png"))); // NOI18N

        lab_time.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        lab_time.setForeground(new java.awt.Color(255, 255, 255));
        lab_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_time.setText("46s");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_return, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lab_time, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lab_time, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_return, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 64)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("请输入管理员密码");

        password.setEditable(false);
        password.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        password.setForeground(new java.awt.Color(251, 205, 57));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setText("jPasswordField1");
        password.setFocusable(false);

        jPanel3.setBackground(new java.awt.Color(251, 205, 57));

        key_1.setBackground(new java.awt.Color(255, 255, 255));
        key_1.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_1.setText("1");

        key_2.setBackground(new java.awt.Color(255, 255, 255));
        key_2.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_2.setText("2");

        key_3.setBackground(new java.awt.Color(255, 255, 255));
        key_3.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_3.setText("3");

        key_4.setBackground(new java.awt.Color(255, 255, 255));
        key_4.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_4.setText("4");

        key_5.setBackground(new java.awt.Color(255, 255, 255));
        key_5.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_5.setText("5");

        key_6.setBackground(new java.awt.Color(255, 255, 255));
        key_6.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_6.setText("6");

        key_7.setBackground(new java.awt.Color(255, 255, 255));
        key_7.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_7.setText("7");

        key_8.setBackground(new java.awt.Color(255, 255, 255));
        key_8.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_8.setText("8");

        key_9.setBackground(new java.awt.Color(255, 255, 255));
        key_9.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_9.setText("9");

        key_0.setBackground(new java.awt.Color(255, 255, 255));
        key_0.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_0.setText("0");

        key_back.setBackground(new java.awt.Color(255, 255, 255));
        key_back.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        key_back.setText("←");

        key_q.setBackground(new java.awt.Color(255, 255, 255));
        key_q.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_q.setText("q");

        key_w.setBackground(new java.awt.Color(255, 255, 255));
        key_w.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_w.setText("w");

        key_e.setBackground(new java.awt.Color(255, 255, 255));
        key_e.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_e.setText("e");

        key_r.setBackground(new java.awt.Color(255, 255, 255));
        key_r.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_r.setText("r");

        key_u.setBackground(new java.awt.Color(255, 255, 255));
        key_u.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_u.setText("u");

        key_i.setBackground(new java.awt.Color(255, 255, 255));
        key_i.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_i.setText("i");

        key_t.setBackground(new java.awt.Color(255, 255, 255));
        key_t.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_t.setText("t");

        key_y.setBackground(new java.awt.Color(255, 255, 255));
        key_y.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_y.setText("y");

        key_o.setBackground(new java.awt.Color(255, 255, 255));
        key_o.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_o.setText("o");

        key_p.setBackground(new java.awt.Color(255, 255, 255));
        key_p.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_p.setText("p");

        key_d.setBackground(new java.awt.Color(255, 255, 255));
        key_d.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_d.setText("d");

        key_f.setBackground(new java.awt.Color(255, 255, 255));
        key_f.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_f.setText("f");

        key_j.setBackground(new java.awt.Color(255, 255, 255));
        key_j.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_j.setText("j");

        key_k.setBackground(new java.awt.Color(255, 255, 255));
        key_k.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_k.setText("k");

        key_g.setBackground(new java.awt.Color(255, 255, 255));
        key_g.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_g.setText("g");

        key_h.setBackground(new java.awt.Color(255, 255, 255));
        key_h.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_h.setText("h");

        key_l.setBackground(new java.awt.Color(255, 255, 255));
        key_l.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_l.setText("l");

        key_a.setBackground(new java.awt.Color(255, 255, 255));
        key_a.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_a.setText("a");

        key_s.setBackground(new java.awt.Color(255, 255, 255));
        key_s.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_s.setText("s");

        key_m.setBackground(new java.awt.Color(255, 255, 255));
        key_m.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_m.setText("m");

        key_change.setBackground(new java.awt.Color(255, 255, 255));
        key_change.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        key_change.setForeground(new java.awt.Color(251, 205, 57));
        key_change.setText("切换");

        key_b.setBackground(new java.awt.Color(255, 255, 255));
        key_b.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_b.setText("b");

        key_n.setBackground(new java.awt.Color(255, 255, 255));
        key_n.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_n.setText("n");

        key_z.setBackground(new java.awt.Color(255, 255, 255));
        key_z.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_z.setText("z");

        key_x.setBackground(new java.awt.Color(255, 255, 255));
        key_x.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_x.setText("x");

        key_c.setBackground(new java.awt.Color(255, 255, 255));
        key_c.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_c.setText("c");

        key_v.setBackground(new java.awt.Color(255, 255, 255));
        key_v.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        key_v.setText("v");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(key_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_back, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(key_q, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_w, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_e, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_r, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_t, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_y, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_u, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_i, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_o, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_p, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(key_a, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_s, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_d, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_f, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_g, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_h, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_j, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_k, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_l, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(key_z, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_x, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_c, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_v, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_b, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_n, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_m, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(key_change, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(key_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(key_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(key_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(key_4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(key_5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(key_6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(key_7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(key_8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(key_9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(key_0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(key_back, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key_q, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_w, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_e, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_r, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_t, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_y, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_u, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_i, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_o, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_p, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key_a, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_s, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_d, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_f, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_g, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_h, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_j, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_k, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key_l, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(key_z, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(key_x, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(key_c, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(key_v, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(key_b, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(key_n, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(key_m, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(key_change, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_return;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton key_0;
    private javax.swing.JButton key_1;
    private javax.swing.JButton key_2;
    private javax.swing.JButton key_3;
    private javax.swing.JButton key_4;
    private javax.swing.JButton key_5;
    private javax.swing.JButton key_6;
    private javax.swing.JButton key_7;
    private javax.swing.JButton key_8;
    private javax.swing.JButton key_9;
    private javax.swing.JButton key_a;
    private javax.swing.JButton key_b;
    private javax.swing.JButton key_back;
    private javax.swing.JButton key_c;
    private javax.swing.JButton key_change;
    private javax.swing.JButton key_d;
    private javax.swing.JButton key_e;
    private javax.swing.JButton key_f;
    private javax.swing.JButton key_g;
    private javax.swing.JButton key_h;
    private javax.swing.JButton key_i;
    private javax.swing.JButton key_j;
    private javax.swing.JButton key_k;
    private javax.swing.JButton key_l;
    private javax.swing.JButton key_m;
    private javax.swing.JButton key_n;
    private javax.swing.JButton key_o;
    private javax.swing.JButton key_p;
    private javax.swing.JButton key_q;
    private javax.swing.JButton key_r;
    private javax.swing.JButton key_s;
    private javax.swing.JButton key_t;
    private javax.swing.JButton key_u;
    private javax.swing.JButton key_v;
    private javax.swing.JButton key_w;
    private javax.swing.JButton key_x;
    private javax.swing.JButton key_y;
    private javax.swing.JButton key_z;
    private javax.swing.JLabel lab_time;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
